CREATE TABLE IF NOT EXISTS auth."user" (
  id BIGSERIAL PRIMARY KEY,
  email_encrypted BYTEA,
  email_hash TEXT UNIQUE,
  password_hash VARCHAR(60) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE
);