CREATE TABLE IF NOT EXISTS app.job (
  id BIGSERIAL PRIMARY KEY,
  situation TEXT NOT NULL,
  document_id INTEGER NOT NULL REFERENCES app.document(id) ON DELETE NO ACTION,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);