CREATE TABLE IF NOT EXISTS ref.role (
  id BIGSERIAL PRIMARY KEY,
  name_ru VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);

