CREATE TABLE IF NOT EXISTS app.job (
  id BIGSERIAL PRIMARY KEY,
  fields JSONB NOT NULL DEFAULT '{}',
  document_id uuid NOT NULL REFERENCES app.document(id) ON DELETE NO ACTION,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);